waifu_reasons = {
    "abigail_williams_(fate)": "Wajahmu menyimpan misteri yang bikin penasaran, mirip Abigail dengan auranya yang menghipnotis.",
    "aegis_(persona)": "Tampangmu kalem dan tajam, kayak android canggih Aegis yang punya hati di balik logikanya.",
    "aisaka_taiga": "Meskipun kelihatan galak, kamu punya sisi manis tersembunyi yang bikin orang pengen deket terus. Taiga vibes banget.",
    "albedo": "Kecerdasan dan sikapmu yang tenang mencerminkan elegannya Albedo. Kamu punya kelas tersendiri.",
    "anastasia_(idolmaster)": "Dingin di luar, hangat di dalam. Aura kamu kayak princess Rusia yang memesona.",
    "aqua_(konosuba)": "Kamu punya energi kocak yang menular, walau kadang chaotic... tapi justru itu daya tarikmu! Persis Aqua.",
    "arcueid_brunestud": "Tatapanmu tajam dan menggoda, menyimpan kekuatan besar di balik senyum manis.",
    "asia_argento": "Wajahmu teduh dan penuh empati, cocok banget sama Asia yang lembut tapi tegar.",
    "astolfo_(fate)": "Energi kamu nggak bisa diprediksi dan selalu bikin suasana hidup. Astolfo approve banget!",
    "asuna_(sao)": "Kamu punya aura pemimpin yang lembut dan setia, cocok banget sama Asuna.",
    "atago_(azur_lane)": "Kamu punya vibe dewasa yang menggoda tapi tetap elegan. Atago banget!",
    "ayanami_rei": "Tatapan kosong tapi dalam. Kamu kayak Rei, misterius tapi punya makna besar di baliknya.",
    "belfast_(azur_lane)": "Sopan, elegan, dan selalu tenang menghadapi apapun. Kamu punya aura maid profesional kelas satu.",
    "bremerton_(azur_lane)": "Sisi sporty dan sedikit bad girl-mu langsung ngingetin kita ke Bremerton yang berani dan seru.",
    "c.c": "Wajahmu kayak nyimpan kontrak rahasia. Kamu misterius, mandiri, dan nggak bisa ditebak.",
    "chitanda_eru": "Matamu penuh rasa ingin tahu dan ekspresif. Kamu kayak Chitanda—selalu penasaran dan memikat.",
    "chloe_von_einzbern": "Senyummu polos tapi nyimpan kekuatan tersembunyi. Chloe vibes detected.",
    "cleveland_(azur_lane)": "Kamu friendly banget, energik, dan penuh semangat kayak kapten yang bisa diandalkan.",
    "d.va_(overwatch)": "Gayamu enerjik dan modern, cocok banget sama gamer idol kayak D.Va.",
    "dido_(azur_lane)": "Kamu pemalu tapi perhatian, kayak Dido yang super loyal tapi suka grogi.",
    "emilia_rezero": "Senyummu menenangkan dan punya aura penyembuh. Emilia banget deh pokoknya.",
    "enterprise_(azur_lane)": "Tatapanmu serius dan penuh tanggung jawab. Kamu kayak kapten kapal perang yang nggak mudah goyah.",
    "formidable_(azur_lane)": "Anggun dan kalem, tapi punya aura powerful. Kamu kayak Formidable: classy but deadly.",
    "fubuki_(one-punch_man)": "Punya wajah kalem tapi jelas terlihat dominan. Kamu leader material kayak Fubuki.",
    "fujibayashi_kyou": "Tampangmu galak dikit, tapi keliatan sayang banget sebenernya. Persis Kyou.",
    "fujiwara_chika": "Ekspresif dan unpredictable. Orang pasti betah karena kamu kayak Chika yang selalu menghibur.",
    "furukawa_nagisa": "Wajahmu hangat dan nenangin hati, cocok banget jadi heroine slice of life kayak Nagisa.",
    "gawr_gura": "Gemesin, lucu, dan selalu ada aja yang random dari kamu. SHAAARK energy!",
    "gilgamesh": "Kamu kelihatan kayak orang yang tahu dirinya keren. Aura raja banget.",
    "giorno_giovanna": "Wajahmu kayak punya misi besar dalam hidup. Giorno vibes... intense dan elegan.",
    "hanekawa_tsubasa": "Tenang dan smart, tapi ada sisi misterius yang gak semua orang tahu.",
    "hatsune_miku": "Kamu kelihatan timeless dan iconic, kayak Miku yang nggak pernah ketinggalan zaman.",
    "hayasaka_ai": "Punya banyak wajah dan bisa adaptasi sama siapa aja. Hayasaka-style!",
    "hirasawa_yui": "Wajahmu nyebarin aura carefree dan bahagia. Kamu kayak ray of sunshine.",
    "hyuuga_hinata": "Kalem dan penyayang, tapi kuat di dalam. Kamu punya kekuatan diam-diam.",
    "ichigo_(darling_in_the_franxx)": "Ekspresimu tegas dan penuh tekad. Ichigo banget, pejuang cinta sejati.",
    "illyasviel_von_einzbern": "Punya sisi childish tapi berani. Kamu lucu tapi nggak bisa diremehkan.",
    "irisviel_von_einzbern": "Anggun, keibuan, dan punya aura pelindung. Kamu kayak cahaya dalam kegelapan.",
    "ishtar_(fate_grand_order)": "Cantik, berbahaya, dan mood swing-nya serem. Tapi justru itu yang bikin kamu menarik.",
    "isshiki_iroha": "Pintar berpura-pura polos. Tapi justru itu daya tarikmu—bikin penasaran.",
    "jonathan_joestar": "Wajahmu jujur dan gentle. Jonathan vibes: laki sejati.",
    "kamado_nezuko": "Punya aura lembut dan wajah imut tapi tersembunyi kekuatan di dalamnya.",
    "kaname_madoka": "Kalem dan idealis. Kamu kayak Madoka yang pengen bantu semua orang.",
    "kanbaru_suruga": "Ekspresimu sporty dan aktif. Kamu kelihatan bebas dan percaya diri.",
    "karin_(blue_archive)": "Sedikit nyentrik, suka gaya sendiri, dan... bawa vibes elite sekaligus awkward.",
    "karna_(fate)": "Kamu punya tatapan seperti pahlawan sunyi. Dingin, tapi berapi-api di dalam.",
    "katsuragi_misato": "Dewasa, berantakan sedikit, tapi super karismatik.",
    "keqing_(genshin_impact)": "Cepat mikir, cepat bergerak. Kamu kelihatan nggak mau kalah dan itu keren!",
    "kirito": "Satu kata: protagonis. Kamu kelihatan kayak orang yang semua orang percaya.",
    "kiryu_coco": "Punya gaya frontal dan out of the box. Kamu beda sendiri dan bangga karenanya.",
    "kizuna_ai": "Virtual, lucu, dan overenergetic. Kamu hidup di masa depan!",
    "kochou_shinobu": "Senyummu lembut tapi bikin deg-degan. Kayak bisa racun dari dalam.",
    "komi_shouko": "Ekspresi awkward tapi manis, bikin orang pengen ngajak ngobrol terus.",
    "laffey_(azur_lane)": "Santai, imut, tapi kayaknya ngantuk terus ya... cocok sama Laffey.",
    "lancer": "Kamu punya aura kesatria. Keren dan tajam, kayak tombak siap menusuk.",
    "makise_kurisu": "Pintar, tsundere, dan... kalau debat pasti menang. Christinaaa!",
    "mash_kyrielight": "Kamu kayak perisai buat orang lain—protective dan reliable.",
    "matou_sakura": "Lembut di luar, penuh luka di dalam. Kamu kayak bunga ungu yang tangguh.",
    "megumin": "Kamu keliatan... agak chaos. Tapi seru. EXPLOSION!",
    "mei_(pokemon)": "Wajahmu optimis dan selalu senyum. Bikin semangat kayak Trainer sejati.",
    "meltlilith": "Kamu kelihatan angkuh, tapi sebenernya cuma pengen dimengerti.",
    "minato_aqua": "Lucu, lincah, dan... kadang nggak ngerti situasi. Tapi lovable banget.",
    "misaka_mikoto": "Kamu punya tekad kuat dan percaya diri. Railgun mood on!",
    "miyazono_kawori": "Kamu bawa aura seni dan tragis romantis yang manis banget.",
    "mori_calliope": "Cool, edgy, dan punya sisi emosional yang dalam. Kayak Reaper bertopeng penyanyi.",
     "nagato_yuki": "Kamu pendiam, misterius, dan cerdas diam-diam. Seperti Nagato yang selalu observan dan siap bertindak saat krusial.",
    "nakano_azusa": "Sisi perfeksionismu terpancar, kamu punya dedikasi tinggi dan fokus kayak Azusa.",
    "nakano_itsuki": "Kamu terlihat keras kepala tapi punya hati yang hangat. Itsuki vibes detected!",
    "nakano_miku": "Pemalu tapi punya pandangan dalam tentang cinta. Kamu kayak Miku yang diem-diem romantis.",
    "nakano_nino": "Sifatmu blak-blakan dan stylish. Orang bisa ilfeel atau jatuh cinta. Kayak Nino banget!",
    "nakano_yotsuba": "Enerjik dan selalu optimis, kamu kayak sunshine-nya grup. Yotsuba banget!",
    "nami_(one_piece)": "Kamu kelihatan cerdas, manipulatif dikit, tapi sangat sayang sama orang dekat. Nami style!",
    "nekomata_okayu": "Kamu chill dan doyan ngemil. Suka kasih vibes cozy kayak Okayu.",
    "nico_robin": "Cerdas, cool, dan sedikit intimidating. Tapi itu justru yang bikin kamu berkelas.",
    "ninomae_ina'nis": "Kamu kelihatan lowkey tapi punya sisi eldritch yang… memikat?",
    "nishikino_maki": "Bisa kelihatan jutek tapi sebenarnya sensitif. Maki mood detected.",
    "okita_souji_(fate)": "Wajahmu lugu tapi bisa jadi mematikan kalau dibutuhkan. Okita-style!",
    "ookami_mio": "Kamu dewasa dan calming, cocok buat jadi kakak panutan kayak Mio.",
    "oshino_ougi": "Kamu suka bikin orang berpikir. Kadang absurd, kadang brilian. Ougi energy!",
    "oshino_shinobu": "Kamu kecil-kecil cabai rawit. Cute tapi ancient. Shinobu feels!",
    "ouro_kronii": "Deadpan kamu bikin suasana hening… tapi lucunya bikin kangen.",
    "paimon_(genshin_impact)": "Suka ngomong, suka makan, dan suka nyebelin... tapi tanpa kamu dunia sepi.",
    "platelet_(hataraku_saibou)": "Kamu kecil, imut, dan sangat rajin. Bikin semua orang bilang 'aww~'.",
    "ram_rezero": "Kamu sarkastik dan to the point. Tapi setia banget kalau udah percaya.",
    "raphtalia": "Kamu punya sifat protektif dan penyayang kayak partner sejati. Raphtalia-core.",
    "rem_rezero": "Kalau kamu cinta, kamu akan berikan segalanya. Rem spirit strong in you.",
    "rias_gremory": "Anggun dan powerful, tapi juga penuh perhatian. Rias energy detected!",
    "rider": "Kamu tenang dan memikat. Mungkin vampir, mungkin bukan. Tapi jelas karismatik.",
    "ryougi_shiki": "Kamu terlihat tenang dan kosong… tapi sebenarnya dalam dan tajam.",
    "sakurajima_mai": "Kamu cuek tapi sangat peduli. Aura artis top tapi rendah hati.",
    "sakurauchi_riko": "Kalem dan pemalu, tapi punya passion besar dalam hal yang kamu suka.",
    "sakura_futaba": "Kamu suka menyendiri tapi cerdas banget. Hacker vibe yang lovable.",
    "satonaka_chie": "Kamu energik dan tomboy, tapi punya hati yang lembut.",
    "semiramis_(fate)": "Kamu anggun, licik, dan suka gaya mewah. Poison queen energy.",
    "sengoku_nadeko": "Pemalu tapi bisa jadi... obsessive. Tapi tetep manis banget.",
    "senjougahara_hitagi": "Kamu dingin dan sarkastik, tapi romantis banget kalau udah terbuka.",
    "shidare_hotaru": "Kamu quirky, nyentrik, dan suka yang unik. Kayak kolektor permen langka.",
    "shinomiya_kaguya": "Pintar dan elegan, kamu suka main strategi dalam urusan hati.",
    "shirakami_fubuki": "Kamu rame dan suka bercanda, tapi tetap bisa jaga keseimbangan.",
    "shirogane_naoto": "Kamu misterius, pintar, dan suka menyelidiki. Detektif vibes kuat banget.",
    "shirogane_noel": "Strong and thicc. Kamu perhatian dan siap melindungi orang lain.",
    "shishiro_botan": "Kamu cool dan chill tapi suka ngegas kalau dibutuhkan. Gamer soul!",
    "shuten_douji_(fate)": "Kamu punya aura memabukkan. Kharismamu kayak sake—nggak semua orang tahan.",
    "sinon": "Kamu punya fokus dan ketenangan. Sniper mental ready.",
    "souryuu_asuka_langley": "Sombong, jago, tapi rapuh. Kamu powerful sekaligus manusiawi.",
    "st_ar-15_(girls_frontline)": "Wajahmu kalem tapi strong, cocok dengan ST AR-15 yang deadly tapi tenang.",
    "super_sonico": "Kamu imut, pemalu, tapi hardworking dan passionate dalam hal yang kamu suka.",
    "suzuhara_lulu": "Kamu chill, punya senyum menenangkan, dan cenderung diem-diem nyimak.",
    "suzumiya_haruhi": "Kamu suka jadi pusat perhatian dan anti biasa-biasa aja. Haruhi banget!",
    "taihou_(azur_lane)": "Possessive dan intens. Tapi kamu juga penuh cinta dan pengorbanan.",
    "takagi-san": "Kamu suka nggodain dan menang terus. Sabar, pintar, dan sedikit jahil.",
    "takamaki_anne": "Ceria, fashionable, dan punya sisi rebel. Queen of duality.",
    "takanashi_rikka": "Kamu dreamy dan suka ngelantur. Tapi hatimu tulus dan peka.",
    "takao_(azur_lane)": "Kamu punya keseimbangan antara cool dan cute. Disiplin tapi lovable.",
    "takarada_rikka": "Kamu stylish tapi nggak ribet. Sedikit tsundere tapi care banget.",
    "takimoto_hifumi": "Kamu introvert banget, tapi punya dunia batin yang indah dan kreatif.",
    "tokoyami_towa": "Dark aura tapi lucu. Kamu kayak penyanyi iblis yang doyan ketawa.",
    "toosaka_rin": "Kamu tsundere klasik. Pintar, kuat, dan punya sisi lembut yang jarang keluar.",
    "toujou_nozomi": "Kamu kelihatan dewasa dan tenang, suka nyentil tapi penuh kasih.",
    "tsushima_yoshiko": "Edgy, cringe, dan bangga. Kamu embrace identitas unikmu kayak Yoshiko.",
    "unicorn_(azur_lane)": "Kamu innocent dan penyayang. Selalu bikin orang pengen ngejaga.",
    "usada_pekora": "Kamu rame banget, absurd, tapi lovable. Peko energy detected!",
    "utsumi_erise": "Kamu kalem dan intelektual. Mikir dalam tapi tetap berkesan simpel.",
    "watson_amelia": "Kamu suka ngulik hal aneh dan absurd. Detektif chaos is you!",
    "waver_velvet": "Kamu keliatan biasa, tapi penuh potensi besar. Underestimated genius.",
    "xenovia_(high_school_dxd)": "Langsung to the point dan kadang terlalu serius. Tapi loyal dan setia.",
    "yuigahama_yui": "Ceria, supel, dan tulus. Kamu selalu bikin suasana jadi lebih ringan.",
    "yui_(angel_beats!)": "Kamu rame, impulsif, tapi punya hati tulus banget.",
    "yukinoshita_yukino": "Sarkastik dan tajam, tapi penuh integritas. Kamu kelihatan dingin, tapi sebenarnya peduli banget.",
    "zero_two_(darling_in_the_franxx)": "Kamu liar, manja, dan cinta banget kalo udah nemu 'darling'-mu. Ikonik dan penuh pesona.",
}
